-- Remove only alerts generated by the retired hard-coded velocity seeder.
-- User-created and production-model alerts are preserved.
DELETE FROM alerts
WHERE (
    title LIKE 'CRITICAL EARLY-WARNING SIGNAL:%'
    OR title LIKE 'EARLY-WARNING SIGNAL:%'
)
AND COALESCE(metadata->>'model_version', '') = '';
